http://localhost:3000/cursos

###

POST http://localhost:3000/cursos HTTP/1.1
Content-Type: application/json

{"nome":"qualquer merda"}
###

DELETE http://localhost:3000/cursos/4
###
PUT http://localhost:3000/cursos/5 HTTP/1.1
Content-Type: application/json

{
    "nome": "C#"
}






